# Generated by Django 5.0.4 on 2024-04-22 19:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asortyment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('typ_produktu', models.CharField(choices=[('szlugi', 'Papierosy'), ('jednorazowki', 'E-papierosy jednorazowe'), ('alkohol lekki', 'Alkohole niski voltage'), ('alkohol gruby', 'Alkohole wysoki voltage')], max_length=100)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=7)),
                ('opis', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100)),
                ('nazwisko', models.CharField(max_length=100)),
                ('wiek', models.IntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)])),
                ('adres', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Zamowienia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('asortyment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monopolowy.asortyment')),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monopolowy.klient')),
            ],
        ),
    ]
