# Generated by Django 5.0.4 on 2024-04-25 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monopolowy', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Zamowienia',
            new_name='Zamowienie',
        ),
        migrations.AlterModelOptions(
            name='asortyment',
            options={'verbose_name_plural': 'Asortyment'},
        ),
        migrations.AlterModelOptions(
            name='klient',
            options={'verbose_name_plural': 'Klienci'},
        ),
        migrations.AlterModelOptions(
            name='zamowienie',
            options={'verbose_name_plural': 'Zamówienia'},
        ),
    ]
