# Generated by Django 5.0.4 on 2024-04-25 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopolowy', '0002_rename_zamowienia_zamowienie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zamowienie',
            name='asortyment',
        ),
        migrations.AddField(
            model_name='zamowienie',
            name='asortyment',
            field=models.ManyToManyField(blank=True, related_name='asortyment', to='monopolowy.asortyment'),
        ),
    ]
