# Generated by Django 5.0.4 on 2024-04-26 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monopolowy', '0004_alter_zamowienie_klient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Klient',
        ),
    ]
