# Generated by Django 5.0.4 on 2024-04-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopolowy', '0005_delete_klient'),
    ]

    operations = [
        migrations.AddField(
            model_name='asortyment',
            name='zdjecie',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
